baseURL = "https://brandarchist.com/"
languageCode = "en-us"
title = "Brandarchist"
theme = "PaperMod"
publishDir = "docs"

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "dark"
  showReadingTime = true
  ShowShareButtons = false
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[[menu.main]]
  name = "Pricing"
  url = "/pricing"
  weight = 1

[[menu.main]]
  name = "Success Stories"
  url = "/success-stories"
  weight = 2

[[menu.main]]
  name = "How It Works"
  url = "/how-it-works"
  weight = 3

[[menu.main]]
  name = "EQ Framework"
  url = "/eq-framework"
  weight = 4

[[menu.main]]
  name = "Book"
  url = "/book"
  weight = 5
