baseURL = "https://brandarchist.com/"
languageCode = "en-us"
title = "Brandarchist"
theme = "PaperMod"
publishDir = "docs"

# Fix HTML rendering for tables or raw HTML
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Turn off annoying noise like date & read time
[params]
  showReadingTime = false
  showDate = false
  hideSummary = true
  env = "production"
  defaultTheme = "dark"

# Menu structure
[[menu.main]]
  name = "Pricing"
  url = "/pricing"
  weight = 1

[[menu.main]]
  name = "EQ Framework"
  url = "/eq-framework"
  weight = 2

[[menu.main]]
  name = "Success Stories"
  url = "/success-stories"
  weight = 3

[[menu.main]]
  name = "Book"
  url = "/book"
  weight = 4
